### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by cwebber** [tonyg/syndicate#35]
Hello!  I don't see a COPYING or LICENSE file in the repo... what license is this project under?  It looks pretty great, so I'd like to know if I can use it!

**Comment by cwebber** [comment]
I see there's https://github.com/tonyg/syndicate/blob/master/hs/LICENSE so I assume that's probably the same license used for the rest of the project?  LGPLv3 or later, same as Racket?  That'd be a solid choice :)

**Comment by tonyg** [comment]
Hi @cwebber! Thanks for pointing this out - it's definitely an omission. You're right that I'd like to use LGPLv3 for the project as a whole. I'll prepare and commit a change to make this clear now.
