### ISSUE TITLE
Changes to Syndicate since the original dissertation, and commercial use

### ISSUE THREAD

**Issue by bobkocisko** [tonyg/syndicate#39]
Hello!  I am evaluating Syndicate for potential inclusion in a commercial project.  I see a large commit history in the project with many commits since the dissertation was originally published and I'm curious if you could provide a high-level overview of what has changed since then?  In particular I am curious if any work has been done to improve the performance of assertion-based interactions which at the time of publication was benchmarked at 2500/s (which may be unusably slow for our needs).  Also I'm curious if any work has been done towards distributed dataspaces (across machine boundaries)?

Finally two questions in a slightly different direction. I'm curious if you are aware of commercial uses of Syndicate, in particular in more demanding performance scenarios?  Also I'm curious how the LGPL license works with closed-source code depending on Syndicate when packaging executables.  Can Syndicate be bundled as a separate shared library to keep our code closed-source or does everything get bundled into the final executable (I'm not familiar with Racket's executable packaging).  I see that Racket transitioned to the MIT license and I'm wondering if you are planning a similar transition for Syndicate?

**Comment by howell** [comment]
Most of those commits are from my work on a typed version of Syndicate. Typed Syndicate is built on top of Syndicate so won't change any understanding you have from reading @tonyg's dissertation.

@tonyg has indeed been working on improving performance and a framework for distribution! You can see some of that work [here](https://github.com/syndicate-lang/syndicate-rkt).

For commercial use, I got the impression that Ray Racine may have incorporated it into a project or two, though I'm not sure on the details. It may have been a personal project. This is based on some discussion from racket-users you can see [here](https://groups.google.com/d/msg/racket-users/IvHqGs-LZkk/wQBkEYZ2BAAJ).

As far as licensing, I'm afraid I'm completely in the dark on that subject. Sorry!

**Comment by bobkocisko** [comment]
Very cool!  Are there examples that use the typed syndicate language that you've been working on?  What would you say is the production-readiness of your work?  Would it be safe to try to integrate it into a production project now?

**Comment by howell** [comment]
There are a couple examples in the repo, such as a [model of the Flink streaming processing system](https://github.com/tonyg/syndicate/blob/master/racket/typed/examples/roles/flink.rkt).

At the moment, it's very much a research prototype. There's at least one major change to the language I'm working on at the moment, and there's a serious problem that I don't think has an easy solution: Typed Syndicate lives in a different universe than Typed Racket. Meaning, Typed Syndicate doesn't understand Typed Racket types, and vice versa.

(Not to mention the complete lack of documentation :<)
