### ISSUE TITLE
Keeping a dataspace alive after 'settling'

### ISSUE THREAD

**Issue by bobkocisko** [tonyg/syndicate#41]
It seems that once all assertions and messages are processed, as long as new assertions or messages are no longer present, the system stops running and returns `#f`.  This is problematic when the system needs to process external events which haven't been explicitly wrapped in an observation of an assertion.  It seems like there should be an idiomatic way to do this but I can't figure it out.

**Comment by howell** [comment]
Dataspace programs have a pool of so-called "ground" assertions used for communicating with the outside world. Most of the drivers operate by using the `send-ground-event` procecure to introduce ground assertions while an actor in the dataspace monitors and reacts to the ground level.

The implementation uses this setup to detect when a program has finished. If all assertions and messages have been processed *and there are no interests in ground assertions* (meaning the dataspace can't/won't react to external events), the dataspace terminates.

Ground assertions live "one level out" from the root dataspace, so they can be manipulated with suitable use of `inbound` and `outbound`. Here's a small program that leverages this fact to prevent exiting:

```
#lang syndicate

(spawn
 (assert (outbound (observe 'hello))))
```

**Comment by bobkocisko** [comment]
That makes sense.  Thanks!
